### PR TITLE
Add select_attributes and skip_attributes to data source

### PR DESCRIPTION
**Pull request by oliverisaac**
- Add select_attributes and skip_attributes to the data source so they aren't super noisy when doing a terraform plan. This is more a convenience function than anything. However, same rules apply: if you `skip_attributes` an attribute then it won't be readable from the data source. 

- Also fixed a bug where terraform would give nil to the attribute hasher which would cause a panic.  I could not figure out why terraform was sending nil to the attribute hasher, but, if it does, then we'll default to 0 rather than panicing.

- And I removed that excess  `Importer` comment you pointed out ;)

### CODE REVIEW

**Comment by trevex** [comment]
As always 👍  from my side.

> Also fixed a bug where terraform would give nil to the attribute hasher which would cause a panic. I could not figure out why terraform was sending nil to the attribute hasher, but, if it does, then we'll default to 0 rather than panicing.

Interesting catch, curious now how and why this happened.

**Comment by oliverisaac** [comment]
This sort of config causes it to panic:

```hcl
terraform {
  required_providers {
    ldap = {
      source  = "trevex/ldap"
      version = "0.3.1"
    }
  }
}

provider "ldap" {
  url           = "ldap://ldap.forumsys.com:389"
  bind_user     = "cn=read-only-admin,dc=example,dc=com"
  bind_password = "password"
  skip_verify   = true
}

resource "ldap_object" "group_1" {
  dn = "cn=test-terraform-1,ou=mathematicians,dc=example,dc=com"
  object_classes = [
    "top",
    "group",
  ]

  select_attributes = [
    "member"
  ]
}

data "ldap_object" "group_2" {
  base_dn = "ou=mathematicians,dc=example,dc=com"
  search_values = {
    DN = ldap_object.group_1.dn
  }
}

resource "ldap_object" "group_2" {
  dn = "cn=test-terraform-2,ou=mathematicians,dc=example,dc=com"
  object_classes = [
    "top",
    "group",
  ]

  attributes = [
    { member = data.ldap_object.group_2.dn }
  ]
  select_attributes = [
    "member"
  ]
}
```

The key is: resource -> data -> resource

Which is a cycle I encountered by chance in a more complex multi-module terraform.

**Comment by oliverisaac** [comment]
Also, of note, 0.3.1 doesn't include the changes it says it does :/

**Comment by oliverisaac** [comment]
Hey, are there any blockers to getting this merged?

**Comment by trevex** [comment]
Sorry just work keeping me busy. Let me take care of this. 👍

**Pull request merged**
